### ISSUE TITLE
Unique id per money event

### ISSUE THREAD

**Issue by matdehaast** [interledgerjs/ilp-protocol-stream#131]
A question was raised by an implementer

> Is there any way native to the Stream protocol or ILP to allow us to individually identify a micropayment?

This can be achieved by raising a unique id within each `money` event. @justmoon pointed out this id could be the SHA256 hash of the ILP packet. It will be a breaking change on the money event though as currently the value returned is an amount value as a string. The newer structure would be along the lines of

```json
{
 "id": "a6f7b874ea69329372ad75353314d7bcacd8c0be365023dab195bcac015d6009",
 "amount": "123"
}
```

Another question is should we amend the spec to mandate this type of functionality for STREAM implementations?

CC @adrianhopebailie @sharafian @sentientwaffle @wilsonianb @justmoon @kincaidoneil

**Comment by adrianhopebailie** [comment]
In theory an ILP packet can have multiple money frames so there COULD be multiple money events per packet?

It seems likely these would be split between streams so as long as there is no expectation that the id is unique across all streams on a connection then this seems workable.

**Comment by sentientwaffle** [comment]
>  Is there any way native to the Stream protocol or ILP to allow us to individually identify a micropayment?

Identify it in what context? To correlate it across the ILP network, or on the STREAM client and server, or something else? Doesn't the execution condition "individually identify a micropayment" or am I missing the point?

I'd prefer a non-breaking change, e.g. pass `{id: "..."}` as an additional argument rather than replacing the `amount`. Changing the spec seems unnecessary since this doesn't necessitate any protocol changes.

**Comment by kincaidoneil** [comment]
Adrian brings up a good point, that a single packet could trigger multiple money events if it sends money over multiple streams.

If we want this to identify a unique micropayment _at the STREAM layer_, I propose the ID be generated via `hmac_256(shared_secret, hmac_256(sequence, stream_id))`
- `shared_secret` ensures the event is unique to that STREAM connection
- `stream_id` ensures the event is unique to the stream it's emitted on
- `sequence` ensures the event if unique to that packet, since STREAM implementations enforce that the sequence is monotonically increasing

**Comment by kincaidoneil** [comment]
> Doesn't the execution condition "individually identify a micropayment" or am I missing the point?

_At the Interledger layer_, I think we should uniquely identify payments with UUIDs. The execution condition doesn't guarantee uniqueness, since a malicious node could send packets with the same condition (for example, this could be bad if each packet is logged, keyed by its condition, and that packet log was later analyzed to determine how much to settle). Alternatively, we could use request IDs generated at the bilateral layer (e.g. the BTP request ID, or an [ILP-over-HTTP request ID](https://github.com/interledger/rfcs/pull/567)).

**Comment by sentientwaffle** [comment]
> The execution condition doesn't guarantee uniqueness, since a malicious node could send packets with the same condition

That's why I was asked what the use case of this request is -- if it's just debugging that might not matter.

**Comment by matdehaast** [comment]
The use case is a Wallet wants a built in mechanism within STREAM money events where each event has a uniqueId. Whilst we know its guaranteed with the implementation to be unique, they would prefer it being sent. 

@kincaidoneil I like your suggestion. How would you envision a model where STREAM raises a money event on the aggregate of packets and not for each packet?

For the ILP layer, the problem we are solving for isn't the ILP level yet. Though we may want to have a way to uniquely identify payments across the entire layer. Lets put that in a seperate issue.

**Comment by kincaidoneil** [comment]
> sequence ensures the event if unique to that packet, since STREAM implementations enforce that the sequence is monotonically increasing

*Caveat here, Rust and Java don't guarantee this, so if the sender were to send multiple packets with the same sequence number, they'd map to the same ID (but I'm not sure why the sender would do that)

> How would you envision a model where STREAM raises a money event on the aggregate of packets and not for each packet?

Seems like more of an application concern rather than a STREAM concern? e.g. subscribe to the event with an RxJS Observable, add filter to debounce or aggregate multiple events

**Comment by matdehaast** [comment]
> Seems like more of an application concern rather than a STREAM concern? e.g. subscribe to the event with an RxJS Observable, add filter to debounce or aggregate multiple events

Fair enough. My concern was more towards STREAM implementations doing that aggregation for you, but the current JS implementation raises them for each STREAM money frame so seems reasonable.

**Comment by matdehaast** [comment]
> `hmac_256(shared_secret, hmac_256(sequence, stream_id))`

@kincaidoneil If I am not mistaken this will only work if we ensure the shared_secret is only allowed to be used once when initiating a STREAM connection. I could easily create a new connection using the same STREAM creds and be able to generate a "duplicate" payment even if its a new one.

**Comment by kincaidoneil** [comment]
Yeah, I think a shared secret must only used for a single connection (_or_ the client must persist its highest sequence number to begin using on subsequent connections). If you don't, there are security issues with replay attacks. Also, if any STREAM packet in the new connection is identical to one sent in the previous connection (which is possible if sequence numbers are re-used!), the generated condition will be the same and money is at risk.

If a client needs to open multiple connections paid to e.g. the same invoice, they should request new credentials, and the server should generate a unique shared secret and address which pays to that invoice.
