### ISSUE TITLE
Support paths with large exchange rates (e.g. big differences in currency scales)

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-protocol-stream#34]
Right now STREAM sends a test packet of 1000 source units to determine the exchange rate. If the amount that arrives is 0, the sender will assume that the path exchange rate is 0 and won't try to send anything through it. We should probably support paths in which the sender and receiver have very different scales.

I think the way to handle this would be:
1. Start with a test packet of 1000
2. If that gets to the receiver, increase the test packet size
3. If the sender gets an `F08: Amount Too Large` error before any money gets to the receiver, then the sender can conclude that no money will be able to be sent through the path

**Comment by kincaidoneil** [comment]
Background: Evan suggested just lowering the asset scale in the Ethereum plugin (e.g., units of microether/szabo instead of wei). While that's obviously a much simpler (partial) solution, @karzak and I tend to think that the asset scale--for consistency and flexibility--should always be the smallest denomination of the given currency. And even if we dropped it from 18 to 6 in the case of ETH, there'll still be cases where there's a very wide discrepancy in exchange rate that need to be dealt with.

For exchange rate calculation, I propose this:

1. Start with a test packet of the default amount.
2. If the response amount is >= 1000 units, calculate the exchange rate and you're done (allow that floor to be user configurable?).
3. If the response amount is < 1000 units, increase the test packet amount by a factor of 10 and try again.
4. After a number of tries (e.g. 20), give up and conclude the exchange rate is 0 (allow number to tries to be configurable?).

I believe this approach is the most robust, as it's able to accommodate the widest range of scaled exchange rates, while still calculating one with a fixed level (e.g. ~4 sig figs) of precision.

(One possible efficiency optimization: if the response amount is 1-9, it could send one test packet of 1000 times the last test packet size (would it be reasonable to assume the response would then be ~1000x larger?) In any case, it'd only cut out 2 roundtrips.)

Questions I have with this approach:
- Would necessitating a 1000 amount in the response shift the exchange rate for paths with a steep liquidity curve as opposed to necessitating only 10 or 100 units?
- Is sending up to 20 unfulfillable packets *bad*? Are there any downsides to that many test packets other than the additional latency?

(A simpler way to put it: what are reasonable defaults for those two parameters?)

**Comment by emschwartz** [comment]
I think we need to adjust the scale for ethereum and come up with better logic for this. Even if we implement a solution like the one proposed here, we don't want XRP -> ETH streams taking ~20 round trips to set up, just because ethereum has a ludicrously small minimum unit. The main reasons to avoid this are latency (which would be noticeable with 20 round trips) and unnecessary load on the network (20 extra packets for many clients will add up).

> paths with a steep liquidity curve

Right now we're assuming that exchange rates are always linear.

Need to think a little more about what the right parameters would be. The idea about requiring the destination amount to be > 1000 is interesting, but it could run into issues like a) what if you don't care about 3 digits of precision on the rate and would prefer for it to connect faster and b) what if the maximum packet amount doesn't let you increase the amount any more?

**Comment by emschwartz** [comment]
> As for the latency: do you have an idea roughly how much each round trip adds?

Even a couple hundred milliseconds would be pretty bad. When designing QUIC, the authors went to great lengths to reduce the number of roundtrips from 2-4 to potentially 1 or 0. We're definitely not operating on the same margins as them but 20 sounds like way too many.

Binary search may not be the worst idea if we have rates that are potentially very large or very small.

**Comment by emschwartz** [comment]
Question: how small of an exchange rate should we support? 10^-{9, 12, 18}? Even smaller than that? Seems like at some point it should just give up.
