### ISSUE TITLE
Determining the exchange rate precision

### ISSUE THREAD

**Issue by traviscrist** [interledgerjs/ilp-protocol-stream#48]
As of right now we are sending out packet amounts of 1, 1000, 1000000, and 1000000000 in an attempt to determine an exchange rate with an amount of precision as quickly as possible. 

At the high level it seems that if we send the following amounts that we have a precision to at least 3 digits and a determined exchange rate: 

| Amount Sent | Prepare Amount | Exchange Rate | 
|--|--|--|
| 1000 | 1000 | 1 |
| 10000 | 1100 | .11 |

However this does not take into account what is actually happening at the connector level. There could be multiple connectors which are changing the rate but since we only know the amount sent and the prepare amount that comes back we cannot see that they have a very different exchange rate so the 1 and .1 are not valid.

Suppose we have the connectors, where their exchange rate is represented in the (): 
```
Conn A <---> (.001) Conn B <---> (1.6) Conn C <---> (1000) Conn D
1000 ----------------> 1 --------------> 1 ---------------> 1000 == 1 

```
In reality the exchange should have been `1000 * .001 * 1.6 * 1000 = 1600` with a rate of 1.6 but on this path the rate calculated was 1. A similar issue could occur with larger amounts as well. 
```
Conn A <---> (.001) Conn B <---> (1.14) Conn C <---> (1000) Conn D
10000 ----------------> 10 --------------> 11 -------------> 1100 == .11
```
This should have been `10000 * .001 * 1.14 * 1000 = 11400` with a rate of 1.14 but was calculated as 1.11.

The issue is that connector C is using a 1.6/1.14 exchange rate but connector B is using a very large exchange rate which effectively takes the value down to 1 and connector D is ramping that back up. 

How can stream determine without having knowledge about the Conn C exchange rate that in these scenarios the calculated exchange rate is incorrect and needs further clarification?

**Comment by kincaidoneil** [comment]
(A table was easier for formatting, but like Travis' examples, imagine a test packet going from connector A to connector D, with the exchange rates in between in parentheses, to show the intermediate packet amounts).

### Case 1

| Conn A | Conn B (0.001) | Conn C (1.14) | Conn D (1000) | Sig Figs | Digits | Exchange Rate | % Change |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 1,000 | 1 | 1 | 1,000 | 1 | 4 | 1 | -- |
| 10,000 | 10 | 11 | 11,000 | 2 | 5 | 1.1 | 9.1% |
| 100,000 | 100 | 114 | 114,000 | 3 | 6 | 1.14 | 3.5% |

### Case 2

| Conn A | Conn B (0.001) | Conn C (1) | Conn D (1000) | Sig Figs | Digits | Exchange Rate | % Change |
| --- | --- | --- | --- | --- | --- | --- | --- |
|  1,000 | 1 | 1 | 1,000 | 1 | 4 | 1 | -- |
| 10,000 | 10 | 10 | 10,000 | 1 | 5 | 1 | 0% |
| 100,000 | 100 | 100 | 100,000 | 1 | 6 | 1 | 0% |

`% change` = (`exchange rate` - `previous exchange rate`) / `exchange rate`
*where `previous exchange rate` used a test packet an order of magnitude less then `exchange rate`
e.g. (1.14 - 1.1) / 1.14 = 0.035, the % change for the 100,000 unit test packet in case 1

My first intuition after thinking about this was, oh, just base the min precision on the number of significant figures, and that solves your problem. But then I thought about, as you also pointed out, cases where the number of significant figures in the exchange rate may be less than that minimum, yet the exchange rate is still correct (like in case 2). In case 2, whether you send a test packet of 1000 units or 1,000,000,000, you'll still get an exchange rate of exactly 1. By contrast in case 1, you get a much different exchange rate between those two sizes of test packets, and certainly an inaccurate exchange rate with the 1000 unit test packet.

If liquidity is assumed to *not* affect the exchange rate at any size of test packet / the exchange rate is constant whether you're sending 1000 units or 1,000,000,000 (another question in itself), one way to solve this is to compare the % change between rounds. In theory, as the test packet size increases, the difference/% change between exchange rates should converge to ~0. So, in essence, setting the precision would just be setting how low the % change needs to be between test packet sizes in order for the exchange rate to be sufficiently precise.

While I think it might ultimately require something akin to this, it's a pretty naive approach (e.g. how should liquidity be assumed to affect the exchange rate? How do you handle cases where it doesn't converge, but is all over the place?).

Also, suppose the case where Conn C had an exchange rate of `1.001`:

| Conn A | Conn B (0.001) | Conn C (1.001) | Conn D (1000) | Sig Figs | Digits | Exchange Rate | % Change |
| --- | --- | --- | --- | --- | --- | --- | --- |
|  1,000 | 1 | 1 | 1,000 | 1 | 4 | 1 | -- |
| 10,000 | 10 | 10 | 10,000 | 1 | 5 | 1 | 0% |
| 100,000 | 100 | 100 | 100,000 | 1 | 6 | 1 | 0% |
| 1,000,000 | 1000 | 1001 | 1,001,000 | 4 | 7 | 1.001 | 0.0009% |
| 10,000,000 | 10,000 | 10,010 | 10,010,000 | 4 | 8 | 1.001 | 0% |

I guess because of the 0s in the effective exchange rate (e.g. `00` in `1.001`), that'll cause the % change to go to 0 *before* the exchange rate actually converges to 0? Hmmmmm.

**Comment by emschwartz** [comment]
This seems like one of those things that we can make arbitrarily complex based on the assumptions we use. My gut feeling is that we should try to stay on the simpler side for now while addressing immediate concerns that arise from how we're actually using this module today.

A couple of assumptions that I would use for now:
- Exchange rate should not change based on size of packet
- Maximum packet amounts will be relatively low (in USD equivalent -- the amounts could be large if the asset uses a really small scale)
- We can stipulate that assets shouldn't be using insanely small scales (like we did in the discussion about the Ethereum plugin using Wei)
- There will likely be only 1-2 connectors applying an exchange rate for the time being

@traviscrist what was the problem you were trying to solve originally with https://github.com/interledgerjs/ilp-protocol-stream/pull/47?

**Comment by traviscrist** [comment]
The problem I was trying to solve in #47 is that when a packet amount of 1000 is sent but fails due to a T04 error and then a packet with the amount of 1 makes it through successfully with a prepareAmount of 1 the current logic uses that 1 -> 1 to calculate an exchange rate of 1. 

This then allows the connection to be established even though the only packet that made it through was an amount of 1 and the exchange rate has 1 digit of precision. The connection then fails to send any packets since it immediately encounters T04 errors with higher amounts like 1000. The simple fix for this was to enforce a minimum precision when determining the exchange rate. When looking into that and thinking about what paths a packet could take the interesting case outlined above that could happen came up in our discussions. 

As Evan mentioned for the time being: 
> - We can stipulate that assets shouldn't be using insanely small scales (like we did in the discussion about the Ethereum plugin using Wei)
> - There will likely be only 1-2 connectors applying an exchange rate for the time being

@kincaidoneil raised some interesting ideas around looking at the percent change but even that as pointed out has its own issues. For now we should go with something simple that solves the issue at hand and then as we run into more real world scenarios we can adjust the stream exchange rate algorithm accordingly. 

For now my proposal is to add the minimum precision option, but change it to only take the right side of the packets prepareAmount into account. This forces that prepareAmount to be at least by default 3 digits of precision and anything less would be rejected and the connection would be unable to establish itself. We can then see how real world scenarios play out and adjust things accordingly. Ill update PR #47 with this change.
